<img src="files/FIC.jpg" width="600" height="460" />

Profesor: Pablo González 


# ÁLGEBRA LINEAL: Matrices y operaciones

# PYTHON COMO CALCULADORA: Operaciones básicas

In [2]:
#Adición
2+3

5

In [3]:
#Sustracción(o resta)
3-7

-4

In [4]:
#Multiplicación
3*20

60

In [5]:
#División Flotante
3/9

0.3333333333333333

In [6]:
#División Entera
5//2

2

In [7]:
#Módulo
7%3

1

In [8]:
#Potencia
2**9

512

### Ejercicio: Calcule el valor de la siguiente expresión usando las operaciones recientemente descritas 
$$\dfrac{1+\dfrac{2}{3}}{1-\dfrac{3}{5}}$$

In [171]:
# Ingrese su código acá

# Matrices con Sympy

Para trabajar con matrices usando Python, tenemos dos opciones. Una de ellas es una Biblioteca de matemática simbólica llamada Sympy. Su propósito es convertirse en un completo sistema de álgebra computacional que pueda competir directamente con alternativas comerciales "Mathematica(Wolframalpha)" y "Maple" manteniendo, a la vez, el código tan simple como sea posible para hacerlo extensible de manera fácil e integral.

## ¿Cómo se ocupa esta Biblioteca para definir matrices?

Ejemplo: Usemos Sympy para definir la matriz $$A=\begin{bmatrix}-1 & 1 \\ 6 & -5\end{bmatrix}$$

In [3]:
#Primer Paso: Importar la biblioteca Sympy
import sympy as sp

In [4]:
# Segundo Paso: Usar el siguiente comando para que 
# la respuesta esté dada con notación matemática
sp.interactive.printing.init_printing(use_latex='mathjax') 

In [12]:
#Tercer Paso: Definir la matriz mediante el comando Matrix
A=sp.Matrix([[-1,1],[6,-5]])
A

⎡-1  1 ⎤
⎢      ⎥
⎣6   -5⎦

In [14]:
#Para obtener el orden de la matriz se puede usar el comando shape
A.shape

(2, 2)

In [172]:
#Para obtener una fila específica podemos usar el comando row
A.row(0)

[-1  1]

In [17]:
#Para obtener una columna específica podemos usar el comando row
A.col(1)

⎡1 ⎤
⎢  ⎥
⎣-5⎦

In [45]:
# Para calcular la traza de una matriz podemos usar el comando trace
sp.trace(A)

-6

# Operaciones Matriciales

In [23]:
M = sp.Matrix([[-1, 4], [2, 3]])
N = sp.Matrix([[3, -1], [20, 7]])
M,N

⎛⎡-1  4⎤  ⎡3   -1⎤⎞
⎜⎢     ⎥, ⎢      ⎥⎟
⎝⎣2   3⎦  ⎣20  7 ⎦⎠

In [24]:
# Suma matricial
M + N

⎡2   3 ⎤
⎢      ⎥
⎣22  10⎦

In [25]:
# Multipliación matricial
M*N

⎡77  29⎤
⎢      ⎥
⎣66  19⎦

In [26]:
# Ponderación
3*M

⎡-3  12⎤
⎢      ⎥
⎣6   9 ⎦

In [27]:
# Potencia de la matriz
M**2

⎡9  8 ⎤
⎢     ⎥
⎣4  17⎦

In [64]:
# Matriz transpuesta
M.T

⎡-1  2⎤
⎢     ⎥
⎣4   3⎦

# Ejemplo

Resuelva la siguiente ecuación matricial
$$
\left[\begin{array}{cccc}3 X^{t}-2 & {\left[\begin{array}{ccc}2 & -1 & 2 \\ -1 & 0 & 1\end{array}\right]}\end{array}\right]^{t}=2 X-3\left[\begin{array}{cc}1 & -1 \\ -1 & 1 \\ 3 & 2\end{array}\right]
$$
Apoye sus cálculos usando Python

In [ ]:
#Ingrese su código acá

# Matrices con Numpy

Uno de los módulos más importantes de Python es Numpy. El origen de Numpy se debe principalmente al diseñador de software Jim Hugunin quien diseñó el módulo Numeric para dotar a Python de capacidades de cálculo similares a las de otros softwares como MATLAB. 

Numpy Es el encargado de añadir toda la capacidad matemática y vectorial a Python haciendo posible operar con cualquier dato numérico o un arreglo. Incorpora operaciones tan básicas como la suma o la multiplicación u otras mucho más complejas como la transformada de Fourier o el álgebra lineal. 

Para definir una matriz con Numpy, el procedimiento es similar al usado con Sympy, el comando también es Matrix. Por ejemplo, definamos la matriz $$R=\begin{bmatrix}1 & -1 & 7 \\ 0 & -1 & 4 \\ 6 & 0 & 9\end{bmatrix}$$



In [65]:
# Importamos la biblioteca numpy
import numpy as np

# Definimos la matriz pedida
R=np.matrix('1 -1 7;0 -1 4; 6 0 9')


print('type(R): ', type(R))
print('R.size: ', R.size)
print('R.shape: ', R.shape)
R

type(R):  <class 'numpy.matrix'>
R.size:  9
R.shape:  (3, 3)


matrix([[ 1, -1,  7],
        [ 0, -1,  4],
        [ 6,  0,  9]])

# Operaciones matriciales (numpy):

In [69]:
S=np.matrix("0 -1 7; 1 1 1; 2 2 2")

# Suma Matricial
R+S

matrix([[ 1, -2, 14],
        [ 1,  0,  5],
        [ 8,  2, 11]])

In [71]:
# Producto Matricial
R*S

matrix([[13, 12, 20],
        [ 7,  7,  7],
        [18, 12, 60]])

In [70]:
# Producto por escalar
(-1)*R

matrix([[-1,  1, -7],
        [ 0,  1, -4],
        [-6,  0, -9]])

In [72]:
# Potencia de una matriz

R**2

matrix([[ 43,   0,  66],
        [ 24,   1,  32],
        [ 60,  -6, 123]])

In [73]:
# Traspuesta de una matriz
R.T

matrix([[ 1,  0,  6],
        [-1, -1,  0],
        [ 7,  4,  9]])

# Ejercicio

Suponga que la matriz $$A=\left[\begin{array}{lllll}0 & 1 & 1 & 0 & 1 \\ 1 & 0 & 0 & 1 & 0 \\ 0 & 1 & 0 & 0 & 0 \\ 1 & 0 & 1 & 0 & 1 \\ 0 & 1 & 1 & 1 & 0\end{array}\right]$$
es la matriz de adyacencia de cierto grafo. Use Python para determinar el número de caminos de largo 3 que conectan los vértices 1 y 3 del mismo.


In [187]:
#Ingrese su código acá

# Excel y Python

Con Python también podemos transformar archivos Excel en matrices y viceversa. Para esto, debemos usar la biblioteca pandas.

In [146]:
# Transformemos un archivo excel a matriz, para esto importamos la biblioteca
import pandas as pd

# Luego, usamos el comando read_excel
d=pd.read_excel("A.xlsx",header=None)
d

0  1
0  1  2
1  3  4

In [147]:
# Finalmente, redefinimos la matriz mediante el comando asarra

d1=np.asarray(d1)
d1

array([[1, 2],
       [3, 4]])

También podemos transformar un archivo excel a una tabla mediante el comando ExcelFile y parse. Veamos un ejemplo

In [148]:
data = pd.ExcelFile('B.xlsx')
B = data.parse("Hoja1")
B

Columna 1  Columna 2
0          1          2
1          3          4

Ahora, para transformar una matriz a un archivo de Excel, debemos usar la biblioteca xlswriter. Veamos el siguiente ejemplo

In [170]:
import xlsxwriter

workbook = xlsxwriter.Workbook('arrays.xlsx')
worksheet = workbook.add_worksheet()

array = [['1', '2', '3'],
         ['4', '5', '6'],
         ['7', '8', '9']]

row = 0

for col, data in enumerate(array):
    worksheet.write_column(row, col, data)

workbook.close()